version: "3.8"

services:
  client:
    build: client
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"

  server:
    build: server
    depends_on:
      - postgres
    environment:
      - DATABASE_URL="postgresql://root:admin@localhost:5432/mydb?schema=public"
    ports:
      - "4000:4000"

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=root
      - POSTGRES_DB=mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persist database data

volumes:
  # Volume to persist Postgres data
  postgres-data: {}
